### ISSUE TITLE
Package creation without rights

### ISSUE THREAD

**Issue by scientific-dev** [Terra-rian/snakecord#2]
You have took the maintainer position without asking the permissions of the original creator permissions with changing the actual `LICENSE` file.

**Comment by Terra-rian** [comment]
The original project was licensed under the [ISC License](https://opensource.org/licenses/ISC), which means that I did not need to ask the original creators if I have permission to maintain it.
> `Permission to use, copy, modify, and/or distribute this software for any purpose with or without fee is hereby granted, provided that the above copyright notice and this permission notice appear in all copies.`

I also credit the original authors, I am simply maintaining this package because I use it quite frequently. I will, however, change the package license to the ISC License, to prevent confusion. The MIT and ISC Licenses are functionally the same, the ISC License is just a bit shorter.
